### ISSUE TITLE
Incomplete C11 support in GCC 4.8 breaks compiling C version

### ISSUE THREAD

**Issue by Simon-L** [enzienaudio/heavy#102]
Hi,

As per this bug, GCC 4.8 (most recent version available on the still very common Ubuntu 14.04) doesn't provide `stdatomic.h`: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016
Which results in this error:

```
$ make
...
heavy/HvUtils.h:266:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
```

Can you suggest a workaround for this?

**Notes:**
- There's yet another issue in 4.8 before that one, `__has_include()` isn't available as preprocessor macro and has to be wrapped in a `defined()` macro.
- On an x86_64 computer (Linuxmint 17.2) I could easily update my compiler version using a PPA: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test _but_ when it comes to more exotic platforms, in my case MIPS32 OpenWRT, upgrading the GCC toolchain is a much longer and more complex task... since building the very toolchain you'll be using is part of the development setup.

**Comment by mhroth** [comment]
Hi @Simon-L, thank you for such a complete bug report!

A fast workaround to your issue is to edit [HvUtils.h](https://github.com/enzienaudio/heavy/blob/master/src/HvUtils.h#L274) to define atomics as:

```
#define hv_atomic_bool volatile bool
#define HV_SPINLOCK_ACQUIRE(_x) _x = true;
#define HV_SPINLOCK_RELEASE(_x) _x = false;
```

If you have more than one thread sending messages into any heavy context then this method may not be entirely reliable, but it is the easiest workaround. If you have only one thread sending messages into a context (and preferably also using a hardware-specific instruction to implement a memory fence in [HvLightPipe.c](https://github.com/enzienaudio/heavy/blob/master/src/HvLightPipe.c#L19)), then you'll be fine.

However, I will also update `HvUtils.h` in the `dev` channel to avoid the GCC issue. I'll let you know when it's done.

**Comment by mhroth** [comment]
@Simon-L if you replace the Atomic section in [HvUtils.h](https://github.com/enzienaudio/heavy/blob/master/src/HvUtils.h#L258) with the following, does your system compile the heavy code?

```
// Atomics
#if HV_WIN
  #include <Windows.h>
  #define hv_atomic_bool volatile LONG
  #define HV_SPINLOCK_ACQUIRE(_x) \
  while (InterlockedCompareExchange(&_x, true, false)) { }
  #define HV_SPINLOCK_RELEASE(_x) (_x = false)
#elif __cplusplus
  #define hv_atomic_bool volatile atomic_bool
  #define HV_SPINLOCK_ACQUIRE(_x) \
  bool expected = false; \
  while (!atomic_compare_exchange_strong(&_x, &expected, true)) { expected = false; }
  #define HV_SPINLOCK_RELEASE(_x) atomic_store(&_x, false)
#elif defined(__has_include)
  #if __has_include(<stdatomic.h>)
    #include <stdatomic.h>
    #define hv_atomic_bool volatile atomic_bool
    #define HV_SPINLOCK_ACQUIRE(_x) \
    bool expected = false; \
    while (!atomic_compare_exchange_strong(&_x, &expected, true)) { expected = false; }
    #define HV_SPINLOCK_RELEASE(_x) atomic_store(&_x, false)
  #else
    #define hv_atomic_bool volatile bool
    #define HV_SPINLOCK_ACQUIRE(_x) _x = true;
    #define HV_SPINLOCK_RELEASE(_x) _x = false;
  #endif
#else
  #define hv_atomic_bool volatile bool
  #define HV_SPINLOCK_ACQUIRE(_x) _x = true;
  #define HV_SPINLOCK_RELEASE(_x) _x = false;
#endif
```

**Comment by mhroth** [comment]
I'm going to close this issue now because to the best of my knowledge it is fixed.
