### ISSUE TITLE
Support abstraction upload

### ISSUE THREAD

**Issue by mhroth** [enzienaudio/heavy#23]

**Comment by woldhek** [comment]
haha i was about to write an email regarding this :) Would be great if you could upload a library of sorts that is referenced as if it was set the same in pd

**Comment by diplojocus** [comment]
We're looking at having the ability to upload a zipped archive (instead of a single file). Inside the archive Heavy would look for a patch named `_main.pd`. Having sub-directories for libraries within the archive would be possible but the referencing would be handled by the user. 

This would mean using [declare --path ./path/to/lib] within the _main patch.
